### ISSUE TITLE
NinjaArsenalBelt Slot 9 not in valid range - [0, 8)

### ISSUE THREAD

**Issue by AqlaSolutions** [Eternal-Team/PortableStorage#12]
### Description
I reorder items in my inventory and afterwise I can't use any items or move.

> 
> [15:08:02] [1/WARN] [tML]: Silently Caught Exception: 
> System.Exception: Slot 9 not in valid range - [0, 8)
>    в ContainerLibrary.ItemHandler.ValidateSlotIndex(Int32 slot) в ContainerLibrary\Item\ItemHandler.cs:строка 238
>    в ContainerLibrary.ItemHandler.GetItemInSlot(Int32 slot) в ContainerLibrary\Item\ItemHandler.cs:строка 70
>    в PortableStorage.Items.Special.NinjaArsenalBelt.UpdateInventory(Player player) в PortableStorage\Items\Special\NinjaArsenalBelt.cs:строка 42
>    в Terraria.ModLoader.ItemLoader.UpdateInventory(Item item, Player player) в tModLoader\Terraria.ModLoader\ItemLoader.cs:строка 873
>    в Terraria.Player.VanillaUpdateInventory(Item item) в tModLoader\Terraria\Player.cs:строка 7881
>    в Terraria.Player.UpdateEquips(Int32 i) в tModLoader\Terraria\Player.cs:строка 10107
>    в DMD<Terraria.Player::Update>(Player , Int32 )
>    в DMD<Terraria.Main::DoUpdate>(Main , GameTime )
>    в BaseLibrary.Hooking.Main_DoUpdate(orig_DoUpdate orig, Main self, GameTime gameTime) в BaseLibrary\Hooking\Hooking.cs:строка 104
>    в 

### Steps to Reproduce

I don't know.

### Expected behavior 

Nothing special.

### Actual behavior

I can't move.

### Reproduction frequency

It's first time on this save but reproduced always after something was broken.

### Versions

Current latest version in mod browser.

### Mods

MagicStorage
Calamity

a lot of others

**Comment by AqlaSolutions** [comment]
I found the mistake, it should be

> Item handlerItem = Handler.GetItemInSlot(j);

instead of 

> Item handlerItem = Handler.GetItemInSlot(i);

in https://github.com/Eternal-Team/PortableStorage/blob/master/Items/Special/NinjaArsenalBelt.cs

**Comment by Itorius** [comment]
Right, thanks for the report.

**Comment by Itorius** [comment]
Closing, not relevant to PS3
