### ISSUE TITLE
Duplication glitch when transfering items out of bags

### ISSUE THREAD

**Issue by MisterPeModder** [Eternal-Team/PortableStorage#3]
### Description

Duplication glitch when shift-clicking items out of bags.

### Steps to Reproduce

1. Open a bag (tested with adventurer bag)
2. Put items inside it
3. Shift-clicking on a stack inside the bag will produce a stack of 9999 items in the inventory
4. Enjoy your dupped items!

### Expected behavior 

The item stack should be tranfered without creating items

### Actual behavior

Shift-clicking an item stack out of a bag changes its amount to 9999.

### Reproduction frequency

Every time.

### Versions

v2.0

### Mods

```
AlchemistNPC
AutoTrash
BaseLibrary
BossChecklist
CalamityMod
CalamityModMusic
ClamExtraMusic
ContainerLibrary
Fargowiltas
FKBossHealthBar
FluidLibrary
LootBags
MagicStorage
NoMoreTombs
PortableStorage
RecipeBrowser
SummonersAssociation
ThoriumMod
WeaponOut
WheresMyItems
WingSlot
WMITF
WorldGenPreviewer
```

**Comment by Itorius** [comment]
This has already been fixed in Portable Storage 2.1 (which I will release today or tomorrow) but thanks for your report anyways ;)
