### ISSUE TITLE
Mod Will Not Load - Invalid IL Code

### ISSUE THREAD

**Issue by FenixFyreX** [Eternal-Team/PortableStorage#6]
### Description

Getting a hard crash when trying to load the mod on Linux (Arch Linux 64bit). Brother can load it on Windows just fine.

### Steps to Reproduce

1. Install tModLoader v0.11.3
2. Install Portable Storage with Dependencies from Mod Browser
3. Literally exit Mod Browser (auto refreshes now, so...)
4. Crash

### Expected behavior 

To actually load and be playable.

### Actual behavior

Crash with an `InvalidProgramException`, saying there is invalid byte code call in the `Player.BuyItem` method.

### Reproduction frequency

Every time.

### Versions

tModLoader 0.11.3
BaseLibrary 1.1.1
FluidLibrary 1.0.3
ContainerLibrary 1.0.3
Portable Storage 2.1.1

### Mods

Just the above in `Versions`.

### Additional Information

Log File: [https://gist.github.com/FenixFyreX/64294bbee5d6cbe448d5c1b9a08d89c1](https://gist.github.com/FenixFyreX/64294bbee5d6cbe448d5c1b9a08d89c1)

**Comment by Itorius** [comment]
Somebody already reported this but I'm unsure as what is causing this bug because it is a Linux only issue.

**Comment by Itorius** [comment]
This should fix the issue so please try it out.

[Mods.zip](https://github.com/Eternal-Team/PortableStorage/files/3478400/Mods.zip)

**Comment by FenixFyreX** [comment]
This worked. What did you alter? I want to know for when I write my own mod(s).
EDIT: Saw the commit. Thanks.

**Comment by FenixFyreX** [comment]
Is it possible for you to bump the version and upload to the Mod Browser officially? I cannot play with my brother on our server unless the mod is signed by the mod browser...

**Comment by Itorius** [comment]
I did (version 2.1.2 iirc). Make sure to update Base Library too.
